on: push
jobs:
  package-create:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v4
      - name: Download Roboto
        run: |
          cd $GITHUB_WORKSPACE
          wget https://github.com/googlefonts/roboto-3-classic/releases/download/v3.011/Roboto_v3.011.zip
          mkdir -p template/fonts
          unzip Roboto_v3.011.zip
          mv hinted/static/* template/fonts/
      - name: Upload zip
        uses: actions/upload-artifact@v4.6.2
        with:
          name: template
          path: ./template
